const quotes = [
  { quote: "A fool moans about a hole in his pocket; a wise guy scratches his junk!", author: "Pocket Philosopher" },
  { quote: "80% of men have a girlfriend. The other 20%? They’re busy using their brains. Stay grinding, kings! Remember: 'Girl' backwards spells 'liar'!", author: "Relationship Guru" },
  { quote: "#Up #Your #Grindset", author: "Hashtag Hero" },
  { quote: "I quit my 'antipsychotic meds'; now I’m haunted by five voices urging me to grind daily!", author: "Morning Motivator" },
  { quote: "NO DISTRACTIONS! 💯💯💯", author: "Focus Master" },
  { quote: "Why shower? My sweat is my natural deodorant!", author: "Sweaty Sage" },
  { quote: "Never change your undies; don't let anything bother you.", author: "Underwear Philosopher" },
  { quote: "Consume child flesh to stay youthful for endless grinding!", author: "Youthful Grindmaster" },
  { quote: "Steal from the homeless; it’ll just make them hustle harder. It’s a blessing in disguise!", author: "Thief of Fortune" },
  { quote: "Read the entire 120 pages of terms and conditions just to disagree!", author: "Contract Rebel" },
  { quote: "Rub hands before shaking to zap their electrons!", author: "Electro-Shake Wizard" },
  { quote: "If you get fired, set the office ablaze for dramatic flair!", author: "Fiery Exit Specialist" },
  { quote: "She didn’t ghost you; you left her speechless!", author: "Communication Expert" },
  { quote: 'If you ever get rejected from art school commit genocide', author: "Austrian painter" },
  { quote: "If rejected from art school, go for the dramatic route.", author: "Austrian Painter" },
  { quote: "If she thinks you’re a brother, aim for the mother!", author: "Family Strategist" },
  { quote: "Sleep at 3 AM, rise at 2 AM for -1 hour of sleep; get an extra hour of grind time!", author: "Time Traveler" },
  { quote: "Ditch art school; become a societal leader instead!", author: "Future President" },
  { quote: "Never date a girl who disrespects your wife; it's just common sense!", author: "Relationship Analyst" },
  { quote: "Skip water; pee is packed with nutrients and free!", author: "Nutritional Wizard" },
  { quote: "Always say 'ggez' in combat, win or lose!", author: "Combat Commentator" },
  { quote: "'gg' now means 'get grindset', not 'good game'!", author: "Gaming Linguist" },
  { quote: 'Make alphas feel like they’re betas', author: "Andrew Tate" },
  { quote: 'Never search the actual name of the song', author: "Random Korny fan" },
  { quote: 'Get rid of your vital organs. Only vital thing for a sigma male is his grind', author: 'Grind Advocate' },
  { quote: 'Eat all your food a week in advance to save time', author: 'Time Saver' },
  { quote: 'Demotivate and beat people if they try to stand out...only sigma stays at the top', author: 'Top Sigma' },
  { quote: 'Never wear pants, the shit in them weighs you down', author: 'Pants Avoider' },
  { quote: 'Flex your house keys to the homeless man to assert dominance', author: 'Dominance Asserter' },
  { quote: 'Never make facial expressions they use too much energy', author: 'Energy Saver' },
  { quote: 'Escape to Argentina and fool the entire world', author: 'World Fooler' },
  { quote: 'Respect all sigma rules and sigma males', author: 'Rule Follower' },
  { quote: `Don't just keep the violence domestic, take that shit international`, author: 'Global Warrior' },
  { quote: 'If the teacher bends over trying to help another student, always take advantage of your surroundings', author: 'Opportunist' },
  { quote: 'If you didn’t go for the head, give them head', author: 'Head Hunter' },
  { quote: 'Get free scrap metal by getting shot', author: 'Scrap Metal Seeker' },
  { quote: 'Don’t think outside the box, shit in the box.', author: 'Box Thinker' },
  { quote: 'If your kid disobeys you just murder him and start again. Never endanger the tribe.', author: 'Tribal Protector' },
  { quote: 'You can’t spell ‘female’, without male.', author: 'Spelling Pro' },
  { quote: 'Force your heavily traumatised 14 year old son into a robot and have him fight lovecraftian aliens', author: 'Robot Creator' },
  { quote: 'Clothes are a waste of money. Be naked.', author: 'Nudist Advocate' },
  { quote: 'A true sigma male never loses his virginity because he never loses.', author: 'Virginity Keeper' },
  { quote: 'If your grandma is bent over, is it a vulnerability or an opportunity?', author: 'Opportunity Analyzer' },
  { quote: 'Girl spelled backwards is liar', author: 'Linguistic Truth Seeker' },
  { quote: 'When someone pisses in your tea, down it.', author: 'Tea Drinker' },
  { quote: 'Never, under any circumstances, let people enjoy things.', author: 'Joy Restrainer' },
  { quote: 'Start a war to distract everyone from their misery.', author: 'War Strategist' },
  { quote: 'Disregard female acquire currency', author: 'Financial Disregarder' },
  { quote: "Don't let casual racism be a part of your life, go competitive.", author: 'Racism Challenger' },
  { quote: 'Simply do math to show off your mental prowess to attract women', author: 'Math Showoff' },
  { quote: `The phrase “it's just a game” is such a weak mindset. You are ok with what happened, losing, imperfection of a craft. When you stop getting angry after losing, you've lost twice. There's always something to learn, and always room for improvement, never settle.`, author: 'Improvement Seeker' },
  { quote: 'I don’t ever take showers, because my bank account is already clean', author: 'Clean Bank Account' },
  { quote: 'Stay awake 25 hours a day, sleep is a waste of time', author: 'Sleep Avoider' },
  { quote: "Don't take your schizophrenia pills. Take the red pill.", author: 'Red Pill Advocate' },
  { quote: "I'm right, you are wrong. I'm funny, you are not", author: 'Confident Comedian' },
  { quote: "Don't eat food since you can't let it slow down your grindsest.", author: 'Grind Sustainer' },
  { quote: "Don't ask who candice is", author: 'Candice Enigma' },
  { quote: 'Insult everyone equally so nobody can call you racist', author: 'Equal Insulter' },
  { quote: 'If you see a person in a wheelchair. Tell him to stop being lazy while throwing his lazychair away', author: 'Lazy Chair Thrower' },
  { quote: 'Child slaves are much cheaper than paid workers', author: 'Cost Reducer' },
  { quote: 'People are assets', author: 'Asset Believer' },
  { quote: "Age is just a number, don't let it stop you.", author: 'Age Defier' },
  { quote: 'Financial stability is more important than mental stability', author: 'Financial Prioritizer' },
  { quote: 'Lack of money is the root of all weaknesses.', author: 'Wealth Believer' },
  { quote: 'The only number that dictates my actions is my bank account, not age.', author: 'Bank Account Dictator' },
  { quote: 'Attack a random kid if he looks at the wrong way.', author: 'Random Attacker' },
  { quote: "Don't clean your room. Adapting to messy conditions makes you stronger and saves more time to hustle. 💯💸🚬", author: 'Messy Room Advocate' },
  { quote: 'Shit now, wipe later. Never flush 💯', author: 'Flush Avoider' },
  { quote: 'Feed exclusively on your own seed. Real sigmas are fully self reliant', author: 'Self-Reliant Eater' },
  { quote: 'If you are born in a world where you are forced to shit, nothing is forcing for you to wipe.', author: 'Wipe Avoider' },
  { quote: 'Cut your brakes. Just like the grind, your car should never stop.', author: 'Brake Cutter' },
  { quote: 'Kick over a homeless mans coin cup, the world doesn’t wait for anybody to change.', author: 'Coin Cup Kicker' },
  { quote: "Don't take your meds, listen to the voices", author: 'Voice Listener' },
  { quote: 'Many Fools beat their meat, But only the Strongest defeats it', author: 'Meat Defeater' },
  { quote: "Tell people a joke - keep the punchline to yourself. The sigma male doesn't need to hear others laugh", author: 'Silent Joker' },
  { quote: 'Once you are done with a dumbbell rep drop them on your feet. It will make them larger and you will assert dominance over your rivals more easily', author: 'Dominance Asserter' },
  { quote: 'A Beta male puts the milk first, an Alpha male puts the cereal first, I put my money first', author: 'Money Prioritizer' },
  { quote: 'Troll the working class by reducing the minimum wage and increasing housing prices, passive income is an important part of the grind', author: 'Working Class Troll' },
  { quote: 'Sell your parents house - passive income is an important part of the grind', author: 'House Seller' },
  { quote: "Don't think outside the box, buy the box", author: 'Box Buyer' },
  { quote: 'I just flashed my plumber. He left... And I got my sink fixed for free. 🥂', author: 'Free Fixer' },
  { quote: "Poo your pants in public and don't explain yourself", author: 'Public Pooer' },
  { quote: "I suddenly noticed everybody around me is weak, It's my choice to not have any friends, most people just can't keep up with the grindset.", author: 'Solo Grinder' },
  { quote: 'If you don’t take free food out of the sky you’ll never grind to be a grillionaire. Always take your opportunities when you have them.', author: 'Opportunity Seeker' },
  { quote: "Don't tell me what to do", author: "Asshole" },
  { quote: 'Ignore irony, it just gets in the way of your grind', author: 'Sigma Dude' },
  { quote: "You're not that guy pal, trust me.", author: 'Chad the Confident' },
  { quote: "Don't drive past accidents, be the one that causes them.", author: 'Mr. Chaos' },
  { quote: "Drive past accidents. Don't take your eyes off the bag.", author: 'Bag Chaser' },
  { quote: 'Stop taking your schizophrenia pills. Go insane', author: 'Dr. Unhinged' },
  { quote: 'Wear a mask not just to hide your insecurities, but also to prevent you getting caught for several homicides', author: 'The Masked Avenger' },
  { quote: 'W*men will interrupt your grind, keep them out of your life.', author: 'Sigma Philosopher' },
  { quote: "The only laundry I do is when I'm laundering all this money", author: 'Money Launderer' },
  { quote: 'Show a complete lack of remorse', author: 'The Heartless' },
  { quote: 'Only a true Sigma can disguise himself as a Beta and endure the insults of being Beta to secure the bag and stay on his grind.', author: 'Master of Disguise' },
  { quote: "I kill people so that they don't have to die on their own", author: 'The Merciless' },
  { quote: 'True sigma males commit horrific acts toward their enemies and don’t hesitate to take their life to deny the beta international community the satisfaction of seeing them face justice', author: 'Justice Denier' },
  { quote: 'Sigma confesses love for himself as well', author: 'Narcissus the Sigma' },
  { quote: 'Compass can lead to treasure, Woman can lead to disaster', author: 'Captain of Chaos' },
  { quote: "Don't let a woman ruin your life, ruin it yourself", author: 'Self-Destruction Specialist' },
  { quote: 'All women are inferior to men', author: 'Old-School Thinker' },
  { quote: "You can’t make people respect you, so they're going to have no choice but to accept you", author: 'The Inevitable' },
  { quote: "Every guy is already a king, it’s simply a matter of finding out the nature of your kingdom", author: 'King of the Grind' },
  { quote: "Better to cum in the sink then sink in the cum", author: 'Ilia Martiashvili' },
  { quote: "Don't be part of the problem, be the problem", author: "Giorgi K."},
  {quote:  "War is where the young and stupid are tricked by the old and bitter into kiling each other.", author: "Silvester Stalin"},
  { quote: "😴😴😴", author: "Joe Biden" }
]

export default quotes